# Generated by Django 4.2.2 on 2023-06-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('sellername', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
